### ISSUE TITLE
GetPositions() for Options

### ISSUE THREAD

**Issue by adrianbegi** [vitali-karmanov/tradier-dotnet-client#4]
I know this is not an official client and the package is only as capable as the underlying API but I was hoping I could be pointed out to a good way to close my open option positions. It seems like GetPositions only returns the symbol for the underlying and not the options ticker so I am unsure how to best know my open options positions in order to close them. I do not currently store any data on my end so once I enter a position on an option I no longer have reference to the option symbol. Any advice would be greatly appreciated as I do understand this is not an issue with the code or package itself. Or am I wrong and does GetPositions return the options symbol?

**Comment by adrianbegi** [comment]
Realized that it does return options symbol

**Comment by vitali-karmanov** [comment]
Hey Adrian

I'm glad you figure it out!

Let us know if you have any questions
