### ISSUE TITLE
Quote Model Uses Inconsistent Types

### ISSUE THREAD

**Issue by Greggat** [vitali-karmanov/tradier-dotnet-client#6]
```cs
    [JsonProperty("close")]
    public object Close { get; set; }
```
This should be numerical type.

Also is there a reason for all the nullables? Does the API not always display them?

Date types are also inconsistent, currently using string/long when it should be DateTime. 

Looks like the model was created with a JSON->C# convertor. I imagine there are similar issues with other models.

**Comment by htedeschi** [comment]
Hey @Greggat, thank you for catching this issue! The issue with the numerical type in the MarketData Quote was fixed and merged. The NuGet package was published to version 1.0.9, make sure to update your project. 

Yes, the reason for nullable properties relates to the fact the API not always displays the data.

Thank you for pointing out the inconsistency with the dates. We extend the invite to you to fork the repo and make changes like these. This will help us to keep up-to-date, and the inconsistency issues like this one can be caught by contributors like you! 🎉
