### ISSUE TITLE
Streaming Implementation

### ISSUE THREAD

**Issue by adrianbegi** [vitali-karmanov/tradier-dotnet-client#7]
Hello, I was just curios if this library provided any streaming examples, either HTTP or Socket, or if there is any plans to implement tradier streaming into the library.

**Comment by htedeschi** [comment]
Hello @adrianbegi, we are implementing the streaming functionalities at the moment. In the next few weeks, we will have something working. Once we have more information and more robust implementation of the streaming functionalities, we will include the documentation in the wiki. Also, shout out to @longpshorn who has implemented a preliminary version for the streaming! His changes should be merged in the master branch really soon. 
Thank you!

**Comment by artemiusgreat** [comment]
Why was this closed if streaming is not implemented?
